export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{
            width: "100%",
            height: "20px",
            backgroundColor: "lightyellow"
          }}
        ></header>
        {children}
        <footer
          style={{
            width: "100%",
            height: "20px",
            backgroundColor: "lightskyblue"
          }}
        ></footer>
      </body>
    </html>
  );
}
